apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stat
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql-service"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: docker.io/library/mysql:latest
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: 'yes'
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi